# HEADER FILE BASED ON: /usr/src/linux-headers-6.8.0-60/include/uapi/linux/net.h

SYS_SOCKET      = 1  # sys_socket(2)
SYS_BIND        = 2  # sys_bind(2)
SYS_CONNECT     = 3  # sys_connect(2)
SYS_LISTEN      = 4  # sys_listen(2)
SYS_ACCEPT      = 5  # sys_accept(2)
SYS_GETSOCKNAME = 6  # sys_getsockname(2)
SYS_GETPEERNAME = 7  # sys_getpeername(2)
SYS_SOCKETPAIR  = 8  # sys_socketpair(2)
SYS_SEND        = 9  # sys_send(2)
SYS_RECV        = 10 # sys_recv(2)
SYS_SENDTO      = 11 # sys_sendto(2)
SYS_RECVFROM    = 12 # sys_recvfrom(2)
SYS_SHUTDOWN    = 13 # sys_shutdown(2)
SYS_SETSOCKOPT  = 14 # sys_setsockopt(2)
SYS_GETSOCKOPT  = 15 # sys_getsockopt(2)
SYS_SENDMSG     = 16 # sys_sendmsg(2)
SYS_RECVMSG     = 17 # sys_recvmsg(2)
SYS_ACCEPT4     = 18 # sys_accept4(2)
SYS_RECVMMSG    = 19 # sys_recvmmsg(2)
SYS_SENDMMSG    = 20 # sys_sendmmsg(2)
